name: catalogadmin Deploy

on:
  push:
    branches: [ main ]  # Trigger on pushes to the main branch (adjust as needed)

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest  # Replace with your preferred runner
    environment: webenv

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checkout code from repository

      - name: Create .env file
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_API_GATEWAY_URL: ${{ secrets.API_GATEWAY_URL }}
          envkey_SERVER_EXCEL_NAME: ${{ secrets.SERVER_EXCEL_NAME }}
          envkey_SERVER_EXCEL_URL: ${{ env.SERVER_EXCEL_URL }}
          file_name: .env
          directory: .
          fail_on_empty: false
          sort_keys: false

      - name: Use .env file
        run: |
          source .env
          echo $API_GATEWAY_URL
          echo $SERVER_EXCEL_NAME
          echo $SERVER_EXCEL_URL

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'beta'
          flutter-version: 3.22.0-0.1.pre

      - name: Enable Flutter Web
        run: flutter config --enable-web

      - name: Clean build directory (optional)
        run: flutter clean

      - name: Install dependencies
        run: flutter pub get

      - name: Build web app
        run: flutter build web --base-href "/catalogadmin/"

      - name: Upload build artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          name: webcatalogmaster-${{ github.run_id }}  # Name for your artifact
          path: build/web  # Path to your built web app files

      - name: Deploy to GitHub Pages
        id: deployment  # Assign an ID for referencing outputs
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: webcatalogmaster-${{ github.run_id }} # Reference uploaded artifact

      - name: Print Deployment URL
        run: |
          echo "**Deployment URL:** ${{ steps.deployment.outputs.page_url }}"
